config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  root to: 'items#index'

  resources :users do
    collection do
      get '/:id/identify', to: 'users#identify'
      get '/:id/logout', to: 'users#logout'
      get '/:id/sales', to: 'users#sales'
      get '/:id/trade/sell', to: "items#trade_sell"
      get '/:id/trade/now', to: "items#trade_now"
      get '/:id/trade/sold', to: "items#trade_sold"
      get '/:id/buy/now', to: "items#buy_now"
      get '/:id/bought', to: "items#bought"
      get '/:id/registrate', to: "cards#registrate"
    end
    resources :reviews, only: [:new, :create]
    resources :cards, only:[:index,:new, :pay]
      collection do
        post '/pay', to: "cards#pay"
      end
  end

  resources :items do
    resources :reviews, only: [:new, :create]
    collection do
      get '/:id/buy', to: 'items#buy'
      get '/:id/buy_confirm', to: 'cards#buy_confirm'
      post '/:id/buy', to: 'cards#buy'
      get '/:id/change', to: 'items#change'
      delete '/:id/change', to: 'items#destroy'
      delete '/trade/now', to: "items#trade_now"
      get '/search', to: 'items#search'
      post '/search', to: 'items#search'
    end
  end

  resources :items do
    resources :comments, only: [:create]
    resources :users, only: [:show]
  end

  patch '/:id/user/identify', to: 'users#identify'

end

app/views/modules/_footer_index.html.haml
%footer.guide__index
  = image_tag (asset_path "mercari.png"), class: "guide__index--image"

app/views/modules/_footer_logo.html.haml
%footer.logo__gray
  = image_tag (asset_path "poricy.png"), class: "exhibit__footer"

app/views/modules/_header_log_in.html.haml
.header-inner
  .upper-box
    = link_to root_path, class: "upper-box__logo" do
      = image_tag (asset_path "logo.png")

    = search_form_for(@search, url: search_items_path) do |f|
      = f.search_field :name_cont, placeholder: "キーワードから探す"
      = fa_icon "search"

  .under-box
    .under-box__left
      %ul.l-left
        %li
          = link_to root_path, class: "from-category" do
            カテゴリーから探す
        %li
          = link_to root_path, class: "from-bland" do
            ブランドから探す
    .under-box__right
      .l-right
        %ul.header-user-nav
          %li
            = link_to user_path(current_user.id), class: "icons" do
              = image_tag (asset_path "member_photo_noimage_thumb.png"), class: "user-icon"
              %span.icon-text
                マイページ
          %li
            = link_to root_path, class: "icons" do
              = fa_icon "bell-o"
              %span.icon-text
                お知らせ
          %li
            = link_to root_path, class: "icons" do
              = fa_icon "check"
              %span.icon-text
                やることリスト

app/views/modules/_header_log_out.html.haml
.header-inner
  .upper-box
    = link_to root_path, class: "upper-box__logo" do
      = image_tag (asset_path "logo.png")

    = search_form_for(@search, url: search_items_path) do |f|
      = f.search_field :name_cont, placeholder: "キーワードから探す"
      = fa_icon "search"

  .under-box
    .under-box__left
      %ul.l-left
        %li
          = link_to root_path, class: "from-category" do
            カテゴリーから探す
        %li
          = link_to root_path, class: "from-bland" do
            ブランドから探す
    .under-box__right
      .l-right
        = link_to new_user_session_path, class: "header-login-btn" do
          ログイン
        = link_to new_user_registration_path, class: "header-signup-btn" do
          新規会員登録

app/views/modules/_header_logo_only.html.haml
%header.signin__header
  = link_to root_path do
    = image_tag (asset_path 'logo.svg'), class: "signin__header--logo"

app/views/modules/_modal.html.haml
.modal
  %h2.modal__content
    確認
  .modal__text
    削除すると二度と復活できません。
    %br 削除する代わりに停止することもできます。
    %br 本当に削除しますか？
  .modal__btn
    .modal__btn--cancel
      .modal__btn--cancel--str
        キャンセル
    = link_to item_path(@item), class: 'modal__btn--delete', method: :delete do
      .modal__btn--delete--str
        削除する

.overlay