config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  root to: 'items#index'

  resources :users do
    collection do
      get '/:id/identify', to: 'users#identify'
      get '/:id/logout', to: 'users#logout'
      get '/:id/sales', to: 'users#sales'
      get '/:id/trade/sell', to: "items#trade_sell"
      get '/:id/trade/now', to: "items#trade_now"
      get '/:id/trade/sold', to: "items#trade_sold"
      get '/:id/buy/now', to: "items#buy_now"
      get '/:id/bought', to: "items#bought"
      get '/:id/registrate', to: "cards#registrate"
    end
    resources :reviews, only: [:new, :create]
    resources :cards, only:[:index,:new, :pay]
      collection do
        post '/pay', to: "cards#pay"
      end
  end

  resources :items do
    resources :reviews, only: [:new, :create]
    collection do
      get '/:id/buy', to: 'items#buy'
      get '/:id/buy_confirm', to: 'cards#buy_confirm'
      post '/:id/buy', to: 'cards#buy'
      get '/:id/change', to: 'items#change'
      delete '/:id/change', to: 'items#destroy'
      delete '/trade/now', to: "items#trade_now"
      get '/search', to: 'items#search'
      post '/search', to: 'items#search'
    end
  end

  resources :items do
    resources :comments, only: [:create]
    resources :users, only: [:show]
  end

  patch '/:id/user/identify', to: 'users#identify'

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :category

  belongs_to :user, optional: true
  belongs_to :size, optional: true
  belongs_to :brand, optional: true

  belongs_to :seller, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true

  has_many :comments
  has_many   :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true

  validates_associated :item_images

  with_options presence: true do |presence|
    presence.validates :name, length: { maximum: 40 }
    presence.validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
    presence.validates :describe, length: { maximum: 1000 }
    presence.validates :status
    presence.validates :burden
    presence.validates :delivery_method
    presence.validates :prefecture
    presence.validates :delivery_day
    presence.validates :category
  end

  enum status:{"新品、未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6}
  enum burden:{"送料込み(出品者負担)":1, "着払い(購入者負担)":2}
  enum delivery_method:{"未定": 1, "らくらくメルカリ便": 2, "ゆうメール": 3, "レターパック": 4, "普通郵便(定形、定形外)": 5, "クロネコヤマト": 6, "ゆうパック": 7, "クリックポスト": 8, "ゆうパケット": 9}
  enum  prefecture: {
    "北海道": 1,"青森県": 2,"岩手県": 3,"宮城県": 4,"秋田県": 5,"山形県": 6,"福島県": 7,
    "茨城県": 8,"栃木県": 9,"群馬県": 10,"埼玉県": 11,"千葉県": 12,"東京都": 13,"神奈川県": 14,
    "新潟県": 15,"富山県": 16,"石川県": 17,"福井県": 18,"山梨県": 19,"長野県": 20,
    "岐阜県": 21,"静岡県": 22,"愛知県": 23,"三重県": 24,
    "滋賀県": 25,"京都府": 26,"大阪府": 27,"兵庫県": 28,"奈良県": 29,"和歌山県": 30,
    "鳥取県": 31,"島根県": 32,"岡山県": 33,"広島県": 34,"山口県": 35,
    "徳島県": 36,"香川県": 37,"愛媛県": 38,"高知県": 39,
    "福岡県": 40,"佐賀県": 41,"長崎県": 42,"熊本県": 43,"大分県": 44,"宮崎県": 45,"鹿児島県": 46,"沖縄県": 47
  }
  enum delivery_day: {"1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3}
  enum trade: {"出品中": 0, "取引中": 1, "売却済": 2}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index

    @categories = Category.all

    ladies_category = Category.find(1)
    ladies = Category.descendants_of ladies_category
    @ladies_items = Item.includes(:item_images).where(category_id: ladies.ids).order("created_at DESC").limit(Image_count)

    mens_category = Category.find(2)
    mens = Category.descendants_of mens_category
    @mens_items = Item.includes(:item_images).where(category_id: mens.ids).order("created_at DESC").limit(Image_count)

    kids_category = Category.find(3)
    kids = Category.descendants_of kids_category
    @kids_items = Item.includes(:item_images).where(category_id: kids.ids).order("created_at DESC").limit(Image_count)

    @chanel_items = Item.includes(:item_images).where(brand_id: 1).order("created_at DESC").limit(Image_count)
    @lui_items = Item.includes(:item_images).where(brand_id: 3).order("created_at DESC").limit(Image_count)
    @sup_items = Item.includes(:item_images).where(brand_id:4).order("created_at DESC").limit(Image_count)
    @nike_items = Item.includes(:item_images).where(brand_id: 2).order("created_at DESC").limit(Image_count)

  end

  def trade_sell
    @items = Item.where(trade:"出品中").where(seller_id: current_user.id)
  end

  def trade_now
    @items = Item.where(trade:"取引中").where(seller_id: current_user.id)
  end

  def trade_sold
    @items = Item.where(trade:"売却済").where(seller_id: current_user.id)
  end

  def buy_now
    @items = Item.where(trade:"取引中").where(buyer_id: current_user.id)
  end

  def bought
    @items = Item.where(trade:"売却済").where(buyer_id: current_user.id)
  end

  def new
    @item = Item.new
    @item.item_images.build

    respond_to do |format|
      format.html
      format.json { @children = Category.children_of(params[:parent_id]) }
    end
  end

  def create
    @item = Item.new(create_params)
    if params[:item][:item_images_attributes] != nil && @item.save(create_params)
      redirect_to action: 'index'
    else
      redirect_to new_item_path
    end
  end

  def show
    @item = Item.find(params[:id])
    @item_images = @item.item_images.limit(Image_count)
    @user = User.find(@item.seller_id)
    @reviews = Review.where(taker_id: @user.id)
    @good_reviews = @reviews.where(review: "良い")
    @normal_reviews = @reviews.where(review: "普通")
    @bad_reviews = @reviews.where(review: "悪い")
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def change
    @item = Item.find(params[:id])
    @item_images = @item.item_images.limit(Image_count)
  end

  def edit
    @item = Item.find(params[:id])
    @set_sub = @item.category.parent
    @set_third = @item.category
    @sub_categories = Category.siblings_of(@item.category.parent)
    @third_categories = Category.siblings_of(@item.category)

    @commission = (@item.price * Commission).floor
    @profit = @item.price - @commission
  end

  def update
    item = Item.find(params[:id])
    if (validate_image == false) && (current_user.id == item.seller_id && user_signed_in?)
      item.update(update_params)
      redirect_to action: 'change'
    else
      redirect_to edit_item_path
    end
  end

  def search
    @search = Item.includes(:user).ransack(params[:q])
    @items = @search.result(distinct: true)
  end

  def change
    @item = Item.find(params[:id])
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy if item.seller_id == current_user.id
    redirect_to "/users/#{current_user.id}/trade/sell"
  end

  private
  def create_params
    params.require(:item).permit(:name, :price, :describe, :size_id, :brand_id, :status, :burden, :delivery_method, :prefecture, :delivery_day, :category_id, item_images_attributes: [:image]).merge(seller_id: current_user.id)
  end

  def update_params
    params.require(:item).permit(:name, :price, :describe, :size_id, :brand_id, :status, :burden, :delivery_method, :prefecture, :delivery_day, :category_id, item_images_attributes: [:id , :item_id, :image, :_destroy]).merge(seller_id: current_user.id)
  end

  def validate_image
    images = params[:item][:item_images_attributes].values
    judge = images.select { |image| image[:_destroy] == "0" || image[:image] }
    return judge.empty?
  end

end

app/views/items/_detail.html.haml
%header
  .header-inner
    .upper-box
      = link_to root_path, class: "upper-box__logo" do
        = image_tag("/assets/logo.png")
      %input.upper-box__search{placeholder: "キーワードから探す", type: "text"}
      = fa_icon "search"
    .under-box
      .under-box__left
        %ul.l-left
          %li
            = link_to root_path, class: "from-category" do
              カテゴリーから探す
          %li
            = link_to root_path, class: "from-bland" do
              ブランドから探す
      .under-box__right
        .l-right
          / = link_to root_path, class: "header-login-btn" do
          /   ログイン
          / = link_to root_path, class: "header-signup-btn" do
          /   新規会員登録
          %ul.header-user-nav
            %li
              = link_to root_path, class: "icons" do
                %img.user-icon{src: "/assets/member_photo_noimage_thumb.png"}
                %span.icon-text
                  マイページ
            %li
              = link_to root_path, class: "icons" do
                = fa_icon "bell-o"
                %span.icon-text
                  お知らせ
            %li
              = link_to root_path, class: "icons" do
                = fa_icon "check"
                %span.icon-text
                  やることリスト


%nav.bread-crumbs
  %ul
    %li{itemscope: true, itemtype: "#"}
      = link_to root_path, itemprop: "url" do
        %span{itemprop: "title"}
          メルカリ
      = fa_icon "chevron-right"
    %li{itemscope: true, itemtype: "#"}
      %span{itemprop: "title"}
        商品詳細ページ

%section.item-detail-container
  %h1.item-detail-container__item-name スノーシューズ レディース 23
  .item-detail-container__main-content
    .item-photo
      .main-image
        = image_tag(asset_path "cloth3.jpg")
      %ul.sub-image
        %li
          = image_tag(asset_path "cloth3.jpg")
        %li
          = image_tag(asset_path "member_photo_noimage_thumb.png")
        %li
          = image_tag(asset_path "cloth3.jpg")
        %li
          = image_tag(asset_path "member_photo_noimage_thumb.png")

    %table.item-detail-table
      %tbody
        %tr
          %th 出品者
          %td
            = link_to root_path do
              みつみみusagi
            .ratings-wrapper
              .item-user-ratings
                = fa_icon "smile-o"
                %span 56
              .item-user-ratings
                = fa_icon "meh-o"
                %span 0
              .item-user-ratings
                = fa_icon "frown-o"
                %span 0
        %tr
          %th カテゴリー
          %td
            = link_to root_path do
              %p レディース
            = link_to root_path do
              .item-detail-table-sub-category
                = fa_icon "chevron-right"
                靴
            = link_to root_path do
              .item-detail-table-sub-sub-category
                = fa_icon "chevron-right"
                ブーツ


        %tr
          %th ブランド
          %td
        %tr
          %th 商品のサイズ
          %td 23cm
        %tr
          %th 商品の状態
          %td 目立った傷や汚れなし
        %tr
          %th 配送料の負担
          %td 送料込み(出品者負担)
        %tr
          %th 配送の方法
          %td らくらくメルカリ便
        %tr
          %th 配送元地域
          %td
            = link_to root_path do
              神奈川県
        %tr
          %th 発送日の目安
          %td 4~7日で発送

  .item-price-box.text-center
    %span.item-price-box__price.bold ¥1.800
    %span.item-price-box__tax (税込)
    %span.item-price-box__fee 送料込み
  .item-buy-btn 購入画面に進む
  / .item-buy-btn.disabled 売り切れました
  .item-description
    %p.item-description-inner
      お値下げします1999円→1800円☆
      %br
      5年前くらいに靴専門店で購入しました☆
      一度、一泊スキー旅行で、そり遊び、雪道歩きに使用しました。
      履き口周辺に若干の毛玉が出来てますが(写真4枚目参照)中敷は汚れなしです☆
      靴底のゴムのすり減りはほとんどなく、状態は良いです☆
      %br
      プチプチに包んで発送致します♪
      %br
      返品は受け付けておりませんので、コメントでお気軽に質問してくださいね(o^^o)
      %br
      中古品になりますので、ご理解頂ける方のみのご購入を、よろしくお願い申し上げます☆
      プロフもご覧くださいね☆

  .item-button-container.clearfix
    .item-button-left
      %button.item-button.item-button-like
        = fa_icon "heart-o", class: "icon-like-border"
        %span いいね!
        %span{"data-num": "like"} 6
      = link_to root_path, class: "item-button item-button-report clearfix" do
        = fa_icon "flag-o"
        %span 不適切な商品の報告
    .item-button-right
      = link_to root_path, class: "safe-commit" do
        = fa_icon "lock"
        %span あんしん・あんぜんへの取り組み

.item-detail-message
  .message-container
    .message-content
      %ul.message-items
        %li.clearfix
          .message-user
            %figure
              .message-user-unknown
                = image_tag asset_path("member_photo_noimage_thumb"), class: "message-user-photo"
              %figcaption.bold

          .message-body
            .message-body-text 出品者がコメントを削除しました
            .message-icons.clearfix
              %time.message-icon-left
                = fa_icon "clock-o"
                %span 2日前
            = fa_icon "comment rotate-90"

        %li.clearfix
          .message-user
            %figure
              .message-user-unknown
                = image_tag asset_path("member_photo_noimage_thumb"), class: "message-user-photo"
              %figcaption.bold

          .message-body
            .message-body-text 出品者がコメントを削除しました
            .message-icons.clearfix
              %time.message-icon-left
                = fa_icon "clock-o"
                %span 2日前
            = fa_icon "comment rotate-90"

    .message-content
      = form_with method: 'POST', class: "message_form" do |f|
        %p
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = f.text_area :name , class: "commentarea-default"
        = f.submit 'コメントする', class: "message-submit comment-btn-default btn-gray"

%ul.nav-other-item-link.clearfix
  %li.nav-item-link-prev
    = link_to root_path do
      = fa_icon "chevron-left"
      ニンジン
  %li.nav-item-link-next
    = link_to root_path do
      大根
      = fa_icon "chevron-right"

.item-social-media-box
  .text-center
  %ul.social-media-box
    %li.social-media-box__icon
      = link_to root_path, class: "share-btn fb-icon" do
        = fa_icon "facebook-official", class: "icon-white p-fixed"
    %li.social-media-box__icon
      = link_to root_path, class: "share-btn tw-icon" do
        = fa_icon "twitter", class: "icon-white"
    %li.social-media-box__icon
      = link_to root_path, class: "share-btn pin-icon" do
        = fa_icon "pinterest", class: "icon-white"

.items-in-user-profile
  %section.items-box-container.clearfix.items-box-overflow
    %h2.items-box-head
      = link_to root_path, class: "extra-items" do
        みつみみusagiさんのその他の出品

    = render "other"

  %section.items-box-container.clearfix.items-box-overflow
    %h2.items-box-head
      = link_to root_path, class: "extra-items" do
        コーチのショルダーバッグ その他の商品

    = render "other"

app/views/items/bought.html.haml
%header
  = render 'modules/header_log_in'
%nav.bread-crumbs
  - breadcrumb :bought
  = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "
%main.prof__l-container.clearfix
  = render 'side/side_bar'
  .transaction__wrapper
    %section.transaction__contents
      %h2 購入した商品
      %ul
        %li.buy__contents
          = link_to "/users/#{current_user.id}/buy/now" do
            %h3.status__default.buy__contents 取引中
        %li.buy__contents
          = link_to "/users/#{current_user.id}/bought"  do
            %h3.status__default.buy__contents.status__select 過去の取引
    .transaction__contents--lists
      %ul.transaction__list
        - if @items.present?
          - @items.each do |item|
            %li
              = link_to new_item_review_path(item), class: "mypage-item-list" do
                - if item.item_images.present?
                  = image_tag (item.item_images.first.image), class: "image-size-default"
                - else
                  = image_tag (asset_path "noimage.gif"), class: "image-size-default"
                .mypage-item-body
                  .mypage-item-body__text
                    = item.name
                  .mypage-item-body__icon
                    .mypage-item-status.action-selling 取引終了
                = fa_icon class: 'fa fa-chevron-right'
        - else
          %li.transaction__list--default.not-found 取引中の商品がございません。

app/views/items/buy.html.haml
%header.signin__header
  = link_to root_path do
    = image_tag (asset_path 'logo.svg'), class: "signin__header--logo"

.buy__single-main
  %section.buy__l-single-container.buy-item-container
    %h2.buy__l-single-head 購入を確定しますか？
    %section.buy__content-buy-item
      .buy-content-item-inner
        %h3.buy-item-image
          = image_tag (asset_path 'm52773408832_1.jpg'), class: 'buy__lazyloaded'
        %p.buy__item-name.bold 商品名
        = form_with class: 'buy__buy-form'
        .buy__buy-form
          %p.buy__price-ja.bold
            ¥ 0
            %span.item-shipping-fee.f14.bold 送料込み
          %ul.buy__buy-accordion
            %li.buy__accordion-parent
              .buy__accordion-toggle-point
                ポイントを使う
                %i
                  = fa_icon 'angle-down', class: 'buy__accordion-icon'

              / JavaScript実装の際に使う
              / %ul.buy__accordion-child
              /   %li.bold 所持ポイント: P 500
              /   %li.form-group
              /     .buy__radio-default
              /       %label
              /         %input{name: "consume_point_radio", type: "radio", value: "none"}
              /         ポイントを使わない
              /     .buy__radio-default
              /       %label
              /         %input{name: "consume_point_radio", type: "radio", value: "all"}
              /         %input{type: "hidden", value: "450"}
              /         すべてのポイントを使う
              /         %br/
              /         P 450
              /     .buy__radio-default
              /       %label
              /         %input{name: "consume_point_radio", type: "radio", value: "partial"}
              /         一部のポイントを使う
              /     %input.buy__input-default{placeholder: "使うポイントを入力", type: "number", :value => ""}
              /     %input{name: "consume_point", type: "hidden", value: "0"}

          %ul.buy__price-table
            %li.buy__price-row.bold
              .buy__price-cell 支払い金額
              %span.buy__price-cell ¥ 0
          .button.btn-default.btn-red.bold
            購入する

    %section.buy__content-user
      .buy__content-user-inner
        %h3.buy__content-user-inner 配送先
        %address.buy__user-info-text
          〒530-0011
          %br/
          大阪府大阪市北区
          大深町０-１
          %br/
          山口 宗一郎
        %p.buy-user-info-text
        = link_to root_path, class: 'buy__user-info-fix' do
          %span 変更する
          = fa_icon 'angle-right', class: 'buy__icon-arrow-right'

    %section.buy__content-user-last
      .buy__content-user-inner
        %h3.buy__content-user-inner 支払い方法
        %p.buy__user-info-text
          ************4242
          %br/
          00 / 00

        = image_tag (asset_path "master-card.svg"), class: 'buy__user-info-card'

        %p
        = link_to root_path, class: 'buy__user-info-fix' do
          %span 変更する
          = fa_icon 'angle-right', class: 'buy__icon-arrow-right'

.poricy
  = image_tag asset_path('poricy.png')

app/views/items/buy_now.html.haml
%header
  = render 'modules/header_log_in'
%nav.bread-crumbs
  - breadcrumb :buy_now
  = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "
%main.prof__l-container.clearfix
  = render 'side/side_bar'
  .transaction__wrapper
    %section.transaction__contents
      %h2 購入した商品
      %ul
        %li.buy__contents
          = link_to "/users/#{current_user.id}/buy/now" do
            %h3.status__default.buy__contents.status__select 取引中
        %li.buy__contents
          = link_to "/users/#{current_user.id}/bought"  do
            %h3.status__default.buy__contents 過去の取引
    .transaction__contents--lists
      %ul.transaction__list
        - if @items.present?
          - @items.each do |item|
            %li
              = link_to new_item_review_path(item), class: "mypage-item-list" do
                - if item.item_images.present?
                  = image_tag (item.item_images.first.image), class: "image-size-default"
                - else
                  = image_tag (asset_path "noimage.gif"), class: "image-size-default"
                .mypage-item-body
                  .mypage-item-body__text
                    = item.name
                  .mypage-item-body__icon
                    .mypage-item-status.action-selling 取引中
                = fa_icon 'chevron-right'
        - else
          %li.transaction__list--default.not-found 取引中の商品がございません。

app/views/items/card.html.haml
.card__contents__wrapper
  %header
    = render 'modules/header_log_in'

  %nav.bread-crumbs
    - breadcrumb :card_add
    = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "

  %main.prof__l-container.clearfix.credit__flexbox
    = render 'side/side_bar'

    .card__wrapper
      %section.card__input--text
        %h2 クレジットカード情報入力
      = form_with method: 'POST', class: "credit__card--form" do |f|
        .card__content
          .card__content--form.card__form--default
            = f.label :カード番号
            %span.card__content--require.card__require--default 必須
            = f.text_field :text, placeholder: "半角数字のみ" , class: "card__input--default"
            %ul.credit__card--list
              %li
              = image_tag (asset_path 'visa.svg'),class: 'card__icon card__visa'
              %li
              = image_tag (asset_path 'master-card.svg'),class: 'card__icon card__master'
              %li
              = image_tag (asset_path 'saison-card.svg'),class: 'card__icon card__saison'
              %li
              = image_tag (asset_path 'jcb.svg'),class: 'card__icon card__jcb'
              %li
              = image_tag (asset_path 'american_express.svg'),class: 'card__icon card__american'
              %li
              = image_tag (asset_path 'dinersclub.svg'),class: 'card__icon card__dinersclub'
              %li
              = image_tag (asset_path 'discover.svg'),class: 'card__icon card__discover'
          .card__expiration--select.card__form--default
            = f.label :有効期限
            %span.card__content--require.card__require--default 必須
            .select__wrapper
              %i.fa.fa-angle-down
              = f.date_select :name, (options = {discard_day: true, discard_year: true,use_month_numbers: true}), { class: "select__year select-default" }
              %span.month__text 月
            .select__wrapper
              %i.fa.fa-angle-down
              = f.date_select :name, (options = {discard_day: true, discard_month: true,use_month_numbers: true, start_year:23, end_year: 30}), { class: "select__year select-default" }
              %span.year__text 年
            .sequrity__code--wrapper
              = f.label :セキュリティコード
              %span.card__content--require.card__require--default 必須
              = f.text_field :name, placeholder: "カード背面4桁もしくは3桁の番号", class: "sequrity__code--box"
            .credit__card--add
              .sequrity__code--qsbox
                %span.card__question ?
              カード裏面の番号とは？
            = f.submit :追加する,class: "credit__card__add--submit"

  %a.sell-btn
    .sell-btn__text 出品
    = fa_icon 'camera'

= render partial: 'modules/footer_index'

app/views/items/card_add.html.haml
.card__contents__wrapper
  %header
    = render 'modules/header_log_in'

  %nav.bread-crumbs
    - breadcrumb :card_add
    = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "

  %main.prof__l-container.clearfix.credit__flexbox
    = render 'side/side_bar'

    .card__wrapper
      %section.card__input--text
        %h2 支払い方法
        .default__card--list
          %section
            .default__card--list-text
              %h3 クレジットカード一覧
        %section.credit__add__wrapper--button
          = link_to root_path, class: "link__add__card" do
            .credit__add__content--button
              %i.fa.fa-credit-card
              クレジットカードを追加する
        .set__payment
          = link_to root_path do
            %span お支払い方法について
            %i.fa.fa-angle-right

  = image_tag (asset_path "mercari.png")

  %a.sell-btn
    .sell-btn__text 出品
    = fa_icon 'camera'

app/views/items/search.html.haml
%header
  - if user_signed_in?
    = render 'modules/header_log_in'
  - else
    = render 'modules/header_log_out'

%nav.bread-crumbs
  - breadcrumb :search
  = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "

%main.top-page-main{role: "main"}
  %section.pickup-container.search__container
    .search__result--head
      - if @items.count == 0
        = "検索結果 0 件"
      - else
        = "検索結果 1-#{@items.count} 件"
    %section.item-box-container
      .items-box-content
        - @items.each do |item|
          %section.items-box
            - if user_signed_in? && item.seller_id == current_user.id
              = link_to edit_item_path(item) do
                .trim
                  = image_tag item.item_images.first.image
                .item-soldout
                  - if item.buyer_id.present?
                    .item-soldout-image
                      %p.sold SOLD
                .items-box-body
                  .items-box-name
                    = item.name
                  .items-box-num
                    .items-box-price
                      = number_to_currency(item.price, locale: 'jp')
                    .items-box-likes
                      = fa_icon 'heart-o'
                      %span 2
                    .item-box-tax (税込)
            - else
              = link_to item_path(item.id) do
                .trim
                  = image_tag item.item_images.first.image
                .item-soldout
                  - if item.buyer_id.present?
                    .item-soldout-image
                      %p.sold SOLD
                .items-box-body
                  .items-box-name
                    = item.name
                  .items-box-num
                    .items-box-price
                      = number_to_currency(item.price, locale: 'jp')
                    .items-box-likes
                      = fa_icon 'heart-o'
                      %span 2
                    .item-box-tax (税込)

= render partial: 'modules/footer_index'

- if user_signed_in?
  = link_to new_item_path, class: "sell-btn" do
    .sell-btn__text 出品
    = fa_icon 'camera'
- else
  = link_to new_user_session_path, class: "sell-btn" do
    .sell-btn__text 出品
    = fa_icon 'camera'

app/views/items/trade_now.html.haml
%header
  = render 'modules/header_log_in'
%nav.bread-crumbs
  - breadcrumb :trade_now
  = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "
%main.prof__l-container.clearfix
  = render 'side/side_bar'
  .transaction__wrapper
    %section.transaction__contents
      %h2 出品した商品
      %ul
        %li
          = link_to "/users/#{current_user.id}/trade/sell" do
            %h3.status__default 出品中
        %li
          = link_to "/users/#{current_user.id}/trade/now"  do
            %h3.status__default.status__select 取引中
        %li
          = link_to "/users/#{current_user.id}/trade/sold" do
            %h3.status__default 売却済み
    .transaction__contents--lists
      %ul.transaction__list
        - if @items.present?
          - @items.each do |item|
            %li
              = link_to "/items/#{item.id}/change", class: "mypage-item-list" do
                - if item.item_images.present?
                  = image_tag (item.item_images.first.image), class: "image-size-default"
                - else
                  = image_tag (asset_path "noimage.gif"), class: "image-size-default"

                .mypage-item-body
                  .mypage-item-body__text
                    = item.name
                  .mypage-item-body__icon
                    .mypage-item-status.action-selling 取引中
                  .request__review
                    %span レビューをしてください
                = fa_icon 'chevron-right'
        - else
          %li.transaction__list--default.not-found 取引中の商品がございません。

= render partial: 'modules/footer_index'