config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'}

  devise_scope :user do
    delete :sign_out, to: 'devise/sessions#destroy'
  end

  root to: 'items#index'

  resources :users do
    collection do
      get '/:id/identify', to: 'users#identify'
      get '/:id/logout', to: 'users#logout'
      get '/:id/sales', to: 'users#sales'
      get '/:id/trade/sell', to: "items#trade_sell"
      get '/:id/trade/now', to: "items#trade_now"
      get '/:id/trade/sold', to: "items#trade_sold"
      get '/:id/buy/now', to: "items#buy_now"
      get '/:id/bought', to: "items#bought"
      get '/:id/registrate', to: "cards#registrate"
    end
    resources :reviews, only: [:new, :create]
    resources :cards, only:[:index,:new, :pay]
      collection do
        post '/pay', to: "cards#pay"
      end
  end

  resources :items do
    resources :reviews, only: [:new, :create]
    collection do
      get '/:id/buy', to: 'items#buy'
      get '/:id/buy_confirm', to: 'cards#buy_confirm'
      post '/:id/buy', to: 'cards#buy'
      get '/:id/change', to: 'items#change'
      delete '/:id/change', to: 'items#destroy'
      delete '/trade/now', to: "items#trade_now"
      get '/search', to: 'items#search'
      post '/search', to: 'items#search'
    end
  end

  resources :items do
    resources :comments, only: [:create]
    resources :users, only: [:show]
  end

  patch '/:id/user/identify', to: 'users#identify'

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery except: :pay

  def index
  end

  def new

  end

  def buy_confirm
    @item = Item.find(params[:id])
    @current_user = User.find(current_user.id)
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    @customer = Payjp::Customer.retrieve(@current_user.pay_id,{
    })
    @last4 = @customer.cards.data[0][:last4]
    @exp_month = @customer.cards.data[0][:exp_month]
    @exp_year = @customer.cards.data[0][:exp_year]
  end

  def registrate
  end

  def pay
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    begin
    token = Payjp::Token.create({
      :card => {
      :number => params["number"],
      :cvc => params["cvc"],
      :exp_month => params["exp_month"],
      :exp_year => params["exp_year"]
     }},
     {
       'X-Payjp-Direct-Token-Generate': 'true'
     }
    )
    rescue Payjp::CardError => e
      body = e.json_body
      err  = body[:error]
    end
    if err.present?
      flash.now[:alert] = "カード情報が不正です"
      return render "registrate"
    end
    customer = Payjp::Customer.create(
       card: token.id,
    )
    user = User.find(current_user.id)
    user[:pay_id] = customer.id
    user.save
    redirect_to :root
  end

  def buy
    @item = Item.find(params[:id])
    if current_user.id != @item.seller_id && current_user.pay_id.present?
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    charge = Payjp::Charge.create(
    :amount => @item.price,
    :customer => current_user.pay_id,
    :currency => 'jpy',
    :capture => 'false'
    )
    else
      return redirect_to root_path, alert:"カードを登録してください。"
    end

    if charge.paid == true
      @item[:buyer_id] = current_user.id
      @item[:trade] = "取引中"
      @item.save
      redirect_to root_path, notice: "決済が完了しました。"
    else
      render :buy, alert: "予期せぬエラーが発生しました。"
    end
    end
end

app/views/cards/buy_confirm.html.haml
%header.signin__header
  = link_to root_path do
    = image_tag (asset_path 'logo.svg'), class: "signin__header--logo"

.buy__single-main
  %section.buy__l-single-container.buy-item-container
    %h2.buy__l-single-head 購入を確定しますか？
    %section.buy__content-buy-item
      .buy-content-item-inner
        %h3.buy-item-image
          - if @item.item_images.present?
            = image_tag @item.item_images.first.image, class: 'buy__lazyloaded'
          - else
            = image_tag (asset_path "noimage.gif"), class: 'buy__lazyloaded'
        %p.buy__item-name.bold
          = @item.name
        = form_with class: 'buy__buy-form'
        .buy__buy-form
          %p.buy__price-ja.bold
            = number_to_currency(@item.price, locale: 'jp')
            - if @item.burden_before_type_cast == 1
              %span.item-shipping-fee.f14.bold 送料込み
            - else @item.burden_before_type_cast == 2
              %span.item-shipping-fee.f14.bold 送料別

          %ul.buy__buy-accordion
            %li.buy__accordion-parent
              .buy__accordion-toggle-point
                ポイントを使う
                %i
                  = fa_icon 'angle-down', class: 'buy__accordion-icon'


          %ul.buy__accordion-child
            %li.user-point.bold
              所持ポイント: P
              %span 500
            %input.buy__input-default{placeholder: "使うポイントを入力", type: "number", value: ""}
            %li.point-alert
              所持ポイントを超えています



          %ul.buy__price-table
            %li.buy__price-row.bold
              .buy__price-cell 支払い金額
              %span.buy__price-cell
                = @item.price
          = link_to "/items/#{@item.id}/buy", method: "POST", data:{confirm: "「#{@item.name}」を購入します。よろしいですか？"} do
            .button.btn-default.btn-red.bold
              購入する

    %section.buy__content-user
      .buy__content-user-inner
        %h3.buy__content-user-inner 配送先
        %address.buy__user-info-text
          = "〒#{@current_user.postal_code}"
          %br/
          = "#{@current_user.prefecture}#{@current_user.city}\n#{@current_user.building_name}#{@current_user.address}"
          %br/
          = "#{@current_user.first_name}#{@current_user.last_name}"
        %p.buy-user-info-text
        = link_to root_path, class: 'buy__user-info-fix' do
          %span 変更する
          = fa_icon 'angle-right', class: 'buy__icon-arrow-right'

    %section.buy__content-user-last
      .buy__content-user-inner
        %h3.buy__content-user-inner 支払い方法
        %p.buy__user-info-text
          = "************#{@last4}"
          %br/
          = "#{@exp_month}/#{@exp_year}"

        = image_tag (asset_path "visa.svg"), class: 'buy__user-info-card'

        %p
        = link_to root_path, class: 'buy__user-info-fix' do
          %span 変更する
          = fa_icon 'angle-right', class: 'buy__icon-arrow-right'

= render partial: 'modules/footer_logo'

app/views/cards/index.html.haml
.card__contents__wrapper
  %header
    = render 'modules/header_log_in'

  %nav.bread-crumbs
    - breadcrumb :card_add
    = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "

  %main.prof__l-container.clearfix.credit__flexbox
    = render 'side/side_bar'

    .card__wrapper
      %section.card__input--text
        %h2 支払い方法
        .default__card--list
          %section
            .default__card--list-text
              %h3 クレジットカード一覧
        %section.credit__add__wrapper--button
          = link_to new_user_card_path(current_user.id), class: "link__add__card" do
            .credit__add__content--button
              %i.fa.fa-credit-card
              クレジットカードを追加する
        .set__payment
          = link_to root_path do
            %span お支払い方法について
            %i.fa.fa-angle-right

  = render partial: 'modules/footer_index'

  %a.sell-btn
    .sell-btn__text 出品
    = fa_icon 'camera'

app/views/cards/new.html.haml
.card__contents__wrapper
  %header
    = render 'modules/header_log_in'

  %nav.bread-crumbs
    - breadcrumb :card_add
    = breadcrumbs class: "breadcrumbs", style: :ul, separator: " #{content_tag(:i, '', :class=>'fa fa-chevron-right')} "

  %main.prof__l-container.clearfix.credit__flexbox
    = render 'side/side_bar'

    .card__wrapper
      %section.card__input--text
        %h2 クレジットカード情報入力
      = form_with method: 'POST',action: "/users/pay", class: "credit__card--form",url:'/users/pay',local:true do |f|
        .card__content
          .card__content--form.card__form--default
            = f.label :カード番号
            %span.card__content--require.card__require--default 必須
            = f.text_field :number, placeholder: "半角数字のみ" , class: "card__input--default", maxlength: 16
            %ul.credit__card--list
              %li
              = image_tag (asset_path 'visa.svg'),class: 'card__icon card__visa'
              %li
              = image_tag (asset_path 'master-card.svg'),class: 'card__icon card__master'
              %li
              = image_tag (asset_path 'saison-card.svg'),class: 'card__icon card__saison'
              %li
              = image_tag (asset_path 'jcb.svg'),class: 'card__icon card__jcb'
              %li
              = image_tag (asset_path 'american_express.svg'),class: 'card__icon card__american'
              %li
              = image_tag (asset_path 'dinersclub.svg'),class: 'card__icon card__dinersclub'
              %li
              = image_tag (asset_path 'discover.svg'),class: 'card__icon card__discover'
          .card__expiration--select.card__form--default
            = f.label :有効期限
            %span.card__content--require.card__require--default 必須
            .select__wrapper
              %i.fa.fa-angle-down
              = f.select :exp_month, [1,2,3,4,5,6,7,8,9,10,11,12], { id: "payment_card_expire_mm" } , { class: "select__month select-default" }
              %span.month__text 月
            .select__wrapper
              %i.fa.fa-angle-down
              = f.select :exp_year, [2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030], { id: "payment_card_expire_mm" } , { class: "select__year select-default" }
              %span.year__text 年
            .sequrity__code--wrapper
              = f.label :セキュリティコード
              %span.card__content--require.card__require--default 必須
              = f.text_field :csv, placeholder: "カード背面4桁もしくは3桁の番号", class: "sequrity__code--box"
            .credit__card--add
              .sequrity__code--qsbox
                %span.card__question ?
              カード裏面の番号とは？
            = f.submit :追加する,class: "credit__card__add--submit"

  = render partial: 'modules/footer_index'

  %a.sell-btn
    .sell-btn__text 出品
    = fa_icon 'camera'

app/views/cards/registrate.html.haml
%header.signin__header
  = link_to root_path do
    = image_tag (asset_path 'logo.svg'), class: "signin__header--logo"

.card__wrapper__top
  %section.card__input--text
    %h2 クレジットカード情報入力
  = form_with method: 'POST',action: "/users/pay", class: "credit__card--form",url:'/users/pay',local:true do |f|
    .card__content
      - if flash.alert.present?
        .alert__invalid
          %li カード情報が不正です
      .card__content--form.card__form--default
        = f.label :カード番号
        %span.card__content--require.card__require--default 必須
        = f.text_field :number, placeholder: "半角数字のみ" , class: "card__input--default", maxlength: 16
        %ul.credit__card--list
          %li
          = image_tag (asset_path 'visa.svg'),class: 'card__icon card__visa'
          %li
          = image_tag (asset_path 'master-card.svg'),class: 'card__icon card__master'
          %li
          = image_tag (asset_path 'saison-card.svg'),class: 'card__icon card__saison'
          %li
          = image_tag (asset_path 'jcb.svg'),class: 'card__icon card__jcb'
          %li
          = image_tag (asset_path 'american_express.svg'),class: 'card__icon card__american'
          %li
          = image_tag (asset_path 'dinersclub.svg'),class: 'card__icon card__dinersclub'
          %li
          = image_tag (asset_path 'discover.svg'),class: 'card__icon card__discover'
      .card__expiration--select.card__form--default
        = f.label :有効期限
        %span.card__content--require.card__require--default 必須
        .select__wrapper
          %i.fa.fa-angle-down
          = f.select :exp_month, [1,2,3,4,5,6,7,8,9,10,11,12], { id: "payment_card_expire_mm" } , { class: "select__month select-default" }
          %span.month__text 月
        .select__wrapper
          %i.fa.fa-angle-down
          = f.select :exp_year, [2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030], { id: "payment_card_expire_mm" } , { class: "select__year select-default" }
          %span.year__text 年
        .sequrity__code--wrapper
          = f.label :セキュリティコード
          %span.card__content--require.card__require--default 必須
          = f.text_field :csv, placeholder: "カード背面4桁もしくは3桁の番号", class: "sequrity__code--box"
        .credit__card--add
          .sequrity__code--qsbox
            %span.card__question ?
          カード裏面の番号とは？
        = f.submit :登録する,class: "credit__card__add--submit"

= render partial: 'modules/footer_logo'